---
name: 'generate-changelog'
description: 'automatically generate a changelog'
author: 'Hank Donnay'
output:
  title:
    description: 'A suggested release title'
  changes:
    description: 'A generated changelog'
runs:
  using: 'node12'
  main: 'dist/index.js'
